### ISSUE TITLE
Documentation doesn't mention how to enable monitoring/metrics

### ISSUE THREAD

**Issue by MarkSRobinson** [gomods/athens-charts#80]
The docs don't seem to mention how to configure/enable metrics. This is super important because they're disabled by default.

**Comment by DrPsychick** [comment]
Enabling metrics is as straight forward as in any other chart, or am I missing something?

https://github.com/gomods/athens-charts/blob/e1a74f29dd20553b99b966310c84b53770b463ff/charts/athens-proxy/values.yaml#L187

**Comment by MarkSRobinson** [comment]
It's obvious to helm experts like us. But for a lot of users who just want to use the chart, they will be intimidated by digging into the chart itself.

I've seen other projects explicitly list all the values that can be set in the documentation.

**Comment by DrPsychick** [comment]
Ok, I understand. 

I think we have several options: 
a) listing all possible values in the README (a table, like in other Helm charts). This would be more effort and needs to be held in sync with every update/change.
b) adding a section about metrics in the existing docs: https://docs.gomods.io/install/install-on-kubernetes/#replicas (which needs a change in the athens repo (https://github.com/gomods/athens/tree/main/docs/content/install)
c) document the possible values in `values.yaml` which is distributed with the chart

I'm not sure if this is worth the invest though. My thinking is that a reliable installation of Athens needs to be "maintained" and operated by people that know what they are doing. Although they are "users" of the Chart, they should not be considered non-technical "users".

So it would help to define the target audience for this change in more detail:
- A software developer : does not need to be a Helm expert, but reading and understanding `values.yaml` in order to deploy Athens (or any other Chart) is required.
- An SRE / DevOps : may also not be a Helm expert, but has likely used Helm in many cases and likely even more familiar with `values.yaml` than a software developer
- ??? : the "user" that needs documentation to deploy a Helm chart, not able to understand `values.yaml` - I would argue such a user should not be responsible for the deployment.

Don't get me wrong, I don't mind adding or extending documentation when it makes sense. We do have to consider though that documentation also needs to be maintained and this is an open source project, maintained by people mostly in their spare time.

With that said, I'd be more than happy to review suggested changes, if someone provides a PR.

**Comment by DrPsychick** [comment]
what might be another option is to automate docs from values: https://github.com/norwoodj/helm-docs

**Comment by DrPsychick** [comment]
I'll close this as we've just merged the updated docs PR. @MarkSRobinson feel free to comment or reopen if you still feel that there is something missing. And thank you very much for triggering this topic!
